name: Validate TypeScript

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Validate TypeScript
        run: npm test
      - name: Validate individual .d.ts files
        run: |
          parallel -v npx tsc --target es6 --noEmit ::: index.d.ts types/*.d.ts
